- charts:
  - clusters:
    - minikube
    configuration:
      values:
        serviceType: ClusterIP
    name: kubernetes-dashboard
    src: https://github.com/kuberlab-catalog/kubernetes-dashboard/
    version: 1.0.0
  name: dashboard
