- charts: []
  name: tf-vb
- charts: []
  name: tf-fb
- charts: []
  name: minio
- charts: []
  name: tensor
- charts:
  - clusters:
    - minikube-ls
    configuration:
      values:
        cpu:
          limits: 100m
          requests: 25m
        image:
          Name: lsheiba/fast-neural-style
          Tag: latest
        memory:
          limits: 2048Mi
          requests: 64Mi
        persistence:
          accessMode: ReadWriteOnce
          enabled: true
          size: 1Gi
        replicas: 1
        serviceType: ClusterIP
    name: fast-neural-style
    src: https://github.com/lsheiba/fast-neural-style/
    version: 1.0.0
  name: fns
