- charts:
  - clusters:
    - minikube
    configuration:
      values:
        serviceType: ClusterIP
    name: kubernetes-dashboard
    src: https://github.com/kuberlab-catalog/kubernetes-dashboard/
    version: 1.0.0
  name: dashboard
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        persistence:
          accessMode: ReadWriteOnce
          enabled: false
          size:
            grafana: 1Gi
            prometheus: 10Gi
          storageClass: anything
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/
    version: 1.0.3
  name: graphana
