- charts:
  - clusters:
    - minikube
    configuration:
      values:
        persistence:
          accessMode: ReadWriteOnce
          enabled: false
          size:
            grafana: 1Gi
            prometheus: 10Gi
          storageClass: anything
        pushGateway:
          enabled: true
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/
    version: 1.3.0
  name: kuberlab
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        cpu:
          limits: 8000m
          requests: 100m
        image:
          Name: lsheiba/fast-neural-style-gpu
          Tag: latest
        memory:
          limits: 16Gi
          requests: 4Gi
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          nfs:
            path: /kuberlab/fast
            server: 192.168.1.55
          size: 16Gi
          storageClass: standard
        replicas: 1
        serviceType: ClusterIP
    name: fast-neural-style-gpu
    src: https://github.com/lsheiba/fast-neural-style-gpu/
    version: 1.0.0
  name: fastgpu
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        cpu:
          limits: 8000m
          requests: 100m
        image:
          Name: lsheiba/fast-neural-style-gpu
          Tag: latest
        memory:
          limits: 16Gi
          requests: 4Gi
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          nfs:
            path: /kuberlab
            server: 192.168.1.55
          size: 16Gi
          storageClass: standard
        replicas: 1
        serviceType: ClusterIP
    name: fast-neural-style-gpu
    src: https://github.com/lsheiba/fast-neural-style-gpu/
    version: 1.0.0
  name: fastgpu2
