- charts: []
  name: tf-vb
- charts: []
  name: tf-fb
- charts: []
  name: minio
- charts: []
  name: tensor
- charts: []
  name: fns
- charts:
  - clusters:
    - minikube-ls
    configuration:
      values:
        cpu:
          limits: 8000m
          requests: 100m
        image:
          Name: lsheiba/fast-neural-style
          Tag: latest
        memory:
          limits: 16Gi
          requests: 64Mi
        persistence:
          accessMode: ReadWriteOnce
          enabled: true
          size: 16Gi
        replicas: 1
        serviceType: ClusterIP
    name: fast-neural-style
    src: https://github.com/lsheiba/fast-neural-style/
    version: 1.0.0
  name: fast
- charts: []
  name: fsj
- charts: []
  name: tfj
