- charts:
  - clusters:
    - minikube
    configuration:
      values:
        serviceType: ClusterIP
    name: kubernetes-dashboard
    src: https://github.com/kuberlab-catalog/kubernetes-dashboard/
    version: 1.0.0
  name: dashboard
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        image: wernight/codiad:alpine
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          nfs:
            path: /kuberlab
            server: 192.168.1.55
          size: 16Gi
          storageClass: standard
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        serviceType: ClusterIP
    name: codiad
    src: https://github.com/kuberlab-catalog/codiad/
    version: 1.0.0
  name: cod
