- charts:
  - clusters:
    - minikube
    configuration:
      values:
        cpu:
          limits: 8000m
          requests: 100m
        image:
          Name: lsheiba/tf-gpu
          Tag: latest
        memory:
          limits: 16Gi
          requests: 64Mi
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          nfs:
            path: /kuberlab/mnist
            server: 192.168.1.55
          size: 16Gi
          storageClass: standard
        replicas: 1
        serviceType: ClusterIP
    name: tensorflow-jupyter
    src: https://github.com/lsheiba/tensorflow-jupyter/
    version: 1.0.0
  name: tfgpu
