- charts: []
  name: tf-vb
- charts:
  - clusters:
    - minikube-ls
    configuration:
      values:
        cpu:
          limits: 8000m
          requests: 25m
        image:
          Name: lsheiba/tensorflow-ls-devel
          Tag: latest
        memory:
          limits: 16Gi
          requests: 64Mi
        persistence:
          accessMode: ReadWriteOnce
          enabled: false
          size: 1Gi
        replicas: 1
        serviceType: ClusterIP
    name: tfj-v3
    src: https://github.com/lsheiba/tfj-v3/
    version: 1.0.0
  name: tf-fb
- charts: []
  name: minio
- charts:
  - clusters:
    - minikube-ls
    configuration:
      values:
        Component: tensorflow-inception
        ContainerPort: 9090
        Image: quay.io/lachie83/inception_serving
        ImagePullPolicy: IfNotPresent
        ImageTag: latest
        Replicas: 1
        Resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        ServicePort: 9090
        ServiceType: LoadBalancer
    name: tensorflow-inception
    src: https://github.com/lsheiba/charts/incubator/tensorflow-inception
    version: 0.1.1
  name: tensor
