- charts:
  - clusters:
    - minikube
    configuration:
      values:
        persistence:
          accessMode: ReadWriteOnce
          enabled: false
          size:
            grafana: 1Gi
            prometheus: 10Gi
          storageClass: anything
        pushGateway:
          enabled: true
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/
    version: 1.3.0
  name: kuberlab
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        image: kuberlab/painter:latest
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        serviceType: ClusterIP
    name: painter
    src: https://github.com/kuberlab-catalog/painter/
    version: 1.0.0
  - clusters:
    - minikube
    configuration:
      values:
        image: kuberlab/painter:latest
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        serviceType: ClusterIP
    name: painter
    src: https://github.com/kuberlab-catalog/painter/
    version: 1.0.0
  name: painter
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        image: wernight/codiad:alpine
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          nfs:
            codiadPath: codiad
            path: /exports
            server: 192.168.1.55
          size: 16Gi
          storageClass: standard
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        serviceType: ClusterIP
    name: codiad
    src: https://github.com/kuberlab-catalog/codiad/
    version: 1.0.1
  name: codiad-t
