- charts:
  - clusters:
    - minikube
    configuration:
      values:
        persistence:
          accessMode: ReadWriteOnce
          enabled: false
          size:
            grafana: 1Gi
            prometheus: 10Gi
          storageClass: anything
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/
    version: 1.0.3
  name: grafana
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        jupyter:
          cpu:
            limits: 8000m
            requests: 100m
          image:
            Name: lsheiba/tensorflow-ls-devel
            Tag: latest
          memory:
            limits: 16Gi
            requests: 64Mi
          serviceType: ClusterIP
        mlboard:
          cpu:
            limits: 1000m
            requests: 100m
          image:
            Name: kuberlab/mlboard
            Tag: latest
          memory:
            limits: 2Gi
            requests: 64Mi
          serviceType: ClusterIP
        tensorboard:
          cpu:
            limits: 1000m
            requests: 100m
          image:
            Name: lsheiba/tensorboard
            Tag: latest
          memory:
            limits: 2Gi
            requests: 64Mi
          serviceType: ClusterIP
        volumes:
          data:
            nfs:
              path: /kuberlab
              server: 192.168.1.55
            size: 16Gi
            storageClass: standard
        workspace: mlboard
    name: mlboard
    src: https://github.com/kuberlab-catalog/ml-board/
    version: 1.0.0
  name: mlboard
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        cpu:
          limits: 8000m
          requests: 100m
        image:
          Name: lsheiba/tensorboard
          Tag: latest
        memory:
          limits: 16Gi
          requests: 64Mi
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          logdir: /notebooks/log_dir
          nfs:
            path: /kuberlab
            server: 192.168.1.55
          size: 16Gi
          storageClass: standard
        replicas: 1
        serviceType: ClusterIP
    name: tensorboard
    src: https://github.com/lsheiba/tensorboard/
    version: 1.0.0
  name: tb1
