- charts:
  - clusters:
    - minikube
    configuration:
      values:
        persistence:
          accessMode: ReadWriteOnce
          enabled: false
          size:
            grafana: 1Gi
            prometheus: 10Gi
          storageClass: anything
    name: grafana-prometheus
    src: https://github.com/kuberlab-catalog/grafana-prometheus/
    version: 1.0.3
  name: grafana
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        image: wernight/codiad:alpine
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          nfs:
            codiadPath: codiad
            path: /kuberlab
            server: 192.168.1.55
          size: 16Gi
          storageClass: standard
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        serviceType: ClusterIP
    name: codiad
    src: https://github.com/kuberlab-catalog/codiad/
    version: 1.0.1
  name: code
- charts:
  - clusters:
    - minikube
    configuration:
      values:
        cpu:
          limits: 8000m
          requests: 100m
        image:
          Name: lsheiba/tf-jupyter-devel-gpu
          Tag: latest
        memory:
          limits: 16Gi
          requests: 4Gi
        persistence:
          accessMode: ReadWriteMany
          enabled: true
          nfs:
            path: /kuberlab/mnist
            server: 192.168.1.55
          size: 16Gi
          storageClass: standard
        replicas: 1
        serviceType: ClusterIP
    name: tensorflow-jupyter-gpu
    src: https://github.com/lsheiba/tensorflow-jupyter-gpu/
    version: 1.0.0
  name: tfgpu
