- charts: []
  name: tf-vebon
- charts: []
  name: tfj-v3
- charts:
  - clusters:
    - minikube-ls
    configuration:
      values:
        cpu:
          limits: 1000m
          requests: 25m
        image:
          Name: lsheiba/tensorflow-ls-devel
          Tag: latest
        memory:
          limits: 8048Mi
          requests: 64Mi
        persistence:
          accessMode: ReadWriteOnce
          enabled: true
          size: 2Gi
        replicas: 1
        serviceType: ClusterIP
    name: tfj-v3
    src: https://github.com/lsheiba/tfj-v3/
    version: 1.0.0
  name: tf-vb
